### ISSUE TITLE
Tests do not support async/await syntax

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/react-async-fetch-lab#2]

**Comment by maxwellbenton** [comment]
Hey @micahshute,

They do now! Turns out the React async labs just needed `babel/polyfill`. Adding in polyfill allows for both Promise based and async/await based solutions to pass the tests, which should resolve this issue.

I've also applied this change to the other [fetch lab](https://github.com/learn-co-curriculum/react-props-and-state-lab). Thanks for spotting this!
