### ISSUE TITLE
npm test persists the fetchMocks from one run to the next, giving an error on later runs.

### ISSUE THREAD

**Issue by arye-eidelman** [learn-co-curriculum/react-async-fetch-lab#3]
Running the test with the watch command - as is used by `npm test` - persists the fetchMocks from one run to the next, giving an error on later runs.

Error: Adding route with same name as existing route.

```
  <App />
    1) "before all" hook

  0 passing (1ms)
  1 failing

  1) <App />
       "before all" hook:
     Error: Adding route with same name as existing route. See `overwriteRoutes` option.
      at Object.FetchMock.addRoute (node_modules/fetch-mock/src/lib/set-up-and-tear-down.js:55:9)
      at Object.FetchMock.mock (node_modules/fetch-mock/src/lib/set-up-and-tear-down.js:22:7)
      at Object.FetchMock.(anonymous function) [as get] (node_modules/fetch-mock/src/lib/set-up-and-tear-down.js:98:15)
      at Context.<anonymous> (test/index.test.js:21:15)
```

test/index.test.js:21 points to `fetchMock.get('*', {people: [{name:"Stimpy"}]})`
```
describe('<App />', () => {
  let appWrapper
  let fetchSpy

  before(() => {
    global.fetch = require('node-fetch')
    fetchMock.get('*', {people: [{name:"Stimpy"}]})
    fetchSpy = spy(global, "fetch")
  })
  // ...
})
```

**Comment by maxwellbenton** [comment]
Hey @arye-dov-eidelman,

Thank you for this issue and for the PR.  I was actually unable to replicate the issue you were experiencing as the existing tests were not causing any issue. However, adding your suggested fix also didn't have any impact and worked the same way. Since your fix has no negative side effects and seems to work for you,  I've gone ahead and merged it in in case other students are experiencing this.

Thank you for contributing!
